version: "{build}"

# all brance build

image:
  - Visual Studio 2017

environment:
  matrix:
    # Cygwin/x64/Release
    - platform: Cygwin x64
      arch: x64
      toolchain: Cygwin
      configuration: Release
      cmake_args: -B ./PrjCygwin -G "Unix Makefiles"

    # Win32/x86/Release
    # - platform: Win32 x86
    #   arch: x86
    #   toolchain: MSVC
    #   configuration: Release
    #   cmake_args: -B ./PrjVisualStudio -G "Visual Studio 15 2017" -A Win32
    #   cmake_build: /verbosity:minimal /maxcpucount

# clone directory
clone_folder: C:\Projects\Skylicht_Engine

# https://www.appveyor.com/docs/windows-images-software
install:
  # clone submodules
  - git submodule update --init --recursive

  # remove conflict sh.exe
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  # set env for python
  - set PATH=C:\Python37;%PATH%

  # set env for cygwin
  - if "%toolchain%"=="Cygwin" set PATH=C:\cygwin64\bin;%PATH%

  # set env for android
  - if "%toolchain%"=="Android" set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%

  # test version
  - cmake --version
  - python --version
  - echo %PATH%
  - echo %platform%
  - echo %APPVEYOR_BUILD_VERSION%

before_build:
  - cd C:\Projects\Skylicht_Engine
  - echo %arch%
  - echo %cmake_args%
  - cmake -S . %cmake_args%

# will be override
build_script:

# will be override
after_build:

# will be override
test_script:

#artifacts:
#  - path: Build\*.zip

for:
  # MSVC
  - matrix:
      only:
        - toolchain: MSVC
    build_script:
      - cd Assets
      - python BuildAssetBundles.py
      - cd ..
      - cmake --build ./PrjVisualStudio --config "%configuration%" -- %cmake_build%
    after_build:
      - mkdir Build
      - dir Bin
      - type Version.txt
      - set /p CONFIG_VERSION=<Version.txt
      - set file_version=%CONFIG_VERSION:.=_%_%APPVEYOR_BUILD_VERSION%
      - set output_zip=SkylichtDemo_%file_version%_%toolchain%_%arch%.zip
      - copy Bin\%configuration%\*.exe Bin
      - cd Bin
      - 7z a %output_zip% *.zip
      - 7z a %output_zip% *.exe
      - cd ..
      - copy Bin\%output_zip% Build
    test_script:
      - cd PrjVisualStudio
      - ctest -C %configuration% --verpose
      - cd ..

  # Cygwin
  - matrix:
      only:
        - toolchain: Cygwin
    build_script:
      - cd Assets
      - python BuildAssetBundles.py
      - cd ..
      - make -C PrjCygwin
    after_build:
      - mkdir Build
      - dir Bin
      - type Version.txt
      - set /p CONFIG_VERSION=<Version.txt
      - set file_version=%CONFIG_VERSION:.=_%_%APPVEYOR_BUILD_VERSION%
      - set output_zip=SkylichtDemo_%file_version%_%toolchain%_%arch%.zip
      - cd Bin
      - 7z a %output_zip% *.zip
      - 7z a %output_zip% *.exe
      - cd ..
      - copy Bin\%output_zip% Build
    test_script:
      - cd PrjCygwin
      - ctest --verpose
      - cd ..
#deploy:
#- provider: GitHub
#  auth_token:
#    secure: the-token-is-hidden-on-purpose
#  force_update: true
#  on:
#    APPVEYOR_REPO_TAG: true
