version: '0.0.{build}'

# all brance build

image:
- Visual Studio 2017

environment:
  matrix:
    # Cygwin/x64/Release
    - platform: Cygwin x86
      arch: x64
      toolchain: Cygwin
      configuration: Release
      cmake_args: -B ./PrjCygwin -G "Unix Makefiles"
      cmake_build: /verbosity:minimal /maxcpucount
      
    # Win32/x64/Release
    - platform: Win32 x64
      arch: x64
      toolchain: MSVC
      configuration: Release      
      cmake_args: -B ./PrjVisualStudio -G "Visual Studio 15 2017" -A x64
      cmake_build: /verbosity:minimal /maxcpucount
      
    # Win32/x86/Release
    - platform: Win32 x86
      arch: x86
      toolchain: MSVC
      configuration: Release
      cmake_args: -B ./PrjVisualStudio -G "Visual Studio 15 2017" -A Win32
      cmake_build: /verbosity:minimal /maxcpucount
      
# clone directory
clone_folder: C:\Projects\Skylicht_Engine

# https://www.appveyor.com/docs/windows-images-software/
install:
  # clone submodules
  - git submodule update --init --recursive
  
  # set env for python
  - set PATH=C:\Python37;%PATH%
  
  # set env for cygwin
  - if "%toolchain%"=="Cygwin" set PATH=C:\cygwin64\bin;%PATH%

  # test version  
  - cmake --version
  - python --version
  - echo %platform%
  
before_build:
  - cd C:\Projects\Skylicht_Engine
  - echo %arch%
  - echo %cmake_args%
  - cmake -S . %cmake_args%

build_script:
  # build visual studio project
  - if "%toolchain%"=="MSVC" (
      cmake --build ./PrjVisualStudio --config "%configuration%" -- %cmake_build%
    )
  - if "%toolchain%"=="Cygwin" (
      make -C PrjCygwin
    )

after_build:
  - mkdir Build
  - set output_zip=Build\Skylicht_%toolchain%_%arch%.zip  
  - if "%toolchain%"=="MSVC" (
      7z a %output_zip% Bin\Windows\Libs\%configuration%\*.lib
    )
  - if "%toolchain%"=="Cygwin" (
      7z a %output_zip% Bin\Windows\Libs\*.a
    )
  
test: off

artifacts:
  - path: Build\*.zip
      
#for:
#  -
    #branches:
    #  only:
    #    - master
    #      configuration: Release
          
    #artifacts:
      # all zip build
      #- path: Build\*.zip
    
    #deploy:
    #- provider: GitHub
    #  auth_token:
    #    secure: the-token-is-hidden-on-purpose
    #  force_update: true
    #  on:
    #    APPVEYOR_REPO_TAG: true