version: '0.0.{build}'

# all brance build

image:
- Visual Studio 2017

environment:
  matrix:
    # Win32/x64/Release
    - platform: Win32 x64
      configuration: Release

    # Win32/x86/Release
    - platform: Win32 x86
      configuration: Release
    
    
# clone directory
clone_folder: C:\Projects\Skylicht_Engine

# https://www.appveyor.com/docs/windows-images-software/
install:
  # clone submodules
  - git submodule update --init --recursive

  # Install a recent CMake
  # - set CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-win64-x64.zip"
  # - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  # - 7z x cmake.zip -oC:\projects\deps > nul
  # - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  # - set PATH=C:\projects\deps\cmake\bin;C:\Python37;%PATH%
  - set PATH=C:\Python37;%PATH%
  - cmake --version
  - python --version
  - echo %PLATFORM%
  - if "%PLATFORM%"=="Win32 x64" ( set generator_arch=x64 )
  - if "%PLATFORM%"=="Win32 x86" ( set generator_arch=Win32 )
  
before_build:
  - cd C:\Projects\Skylicht_Engine
  - echo %generator_arch%
  - echo %cmake_args%
  - cmake %cmake_args% -S . -B ./PrjVisualStudio -G "Visual Studio 15 2017" -A %generator_arch%

build_script:
  - cmake --build ./PrjVisualStudio --config "%configuration%" -- /verbosity:minimal /maxcpucount
  
#build:
#  project: C:\Projects\Skylicht_Engine\PrjVisualStudio\SKYLICHT_ENGINE.sln
#  verbosity: minimal
#  parallel: true

after_build:

test: off

artifacts:
  - path: C:\Projects\Skylicht_Engine\Bin\Windows\Libs\$(configuration)\Irrlicht.lib
    name: Irrlicht
    
#deploy:
#- provider: GitHub
#  auth_token:
#    secure: the-token-is-hidden-on-purpose
#  force_update: true
#  on:
#    APPVEYOR_REPO_TAG: true