version: '0.0.{build}'

# all brance build

image:
- Visual Studio 2017

environment:
  matrix:
    # Win32/x64/Release
    - platform: Win32 x64
      configuration: Release

    # Win32/x86/Release
    - platform: Win32 x86
      configuration: Release
    
    
# clone directory
clone_folder: C:\Projects\Skylicht_Engine

# https://www.appveyor.com/docs/windows-images-software/
install:
  # clone submodules
  - git submodule update --init --recursive
  
  - set PATH=C:\Python37;%PATH%
  - cmake --version
  - python --version
  - echo %PLATFORM%
  - if "%PLATFORM%"=="Win32 x64" ( set generator_arch=x64 )
  - if "%PLATFORM%"=="Win32 x86" ( set generator_arch=Win32 )
  
before_build:
  - cd C:\Projects\Skylicht_Engine
  - echo %generator_arch%
  - echo %cmake_args%
  - cmake %cmake_args% -S . -B ./PrjVisualStudio -G "Visual Studio 15 2017" -A %generator_arch%

build_script:
  - if "%PLATFORM%"=="Win32 x64" (
      cmake --build ./PrjVisualStudio --config "%configuration%" -- /verbosity:minimal /maxcpucount
    )
    
  - if "%PLATFORM%"=="Win32 x86" (
      cmake --build ./PrjVisualStudio --config "%configuration%" -- /verbosity:minimal /maxcpucount
    )

after_build:

test: off

artifacts:
  - path: Bin\Windows\Libs\$(configuration)\Irrlicht.lib
    name: Irrlicht
    
#deploy:
#- provider: GitHub
#  auth_token:
#    secure: the-token-is-hidden-on-purpose
#  force_update: true
#  on:
#    APPVEYOR_REPO_TAG: true