version: 2.1

commands:  
  build-engine-native:
    steps:
      - run:
          command: >
            cmake -S. -BPrjAndroid-$ABI -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=$ABI -DANDROID_ARM_NEON=ON -DANDROID_NATIVE_API_LEVEL=26

            make -C PrjAndroid-$ABI
          name: Build Skylicht Engine (NDK)
  build-asset-bundles:
    steps:
      - run:
          command:  > 
            cd Assets

            chmod +x ../Tools/PVRTexTool/linux/PVRTexToolCLI

            sudo apt install python-pip

            python -m pip install tinydb
          
            python -m pip install Pillow

            python BuildTextureCompressETC.py

            python BuildAssetBundles.py

            cd ..
          name: Build Assets, ETC Textures
  build-android-apk:
    steps:
      - run:
          command: >
            export ANDROID_ASSET_PATH=Projects/Android/app/src/main/assets

            export ANDROID_JNILIBS_PATH=Projects/Android/app/src/main/jniLibs

            mkdir $ANDROID_JNILIBS_PATH

            mkdir $ANDROID_JNILIBS_PATH/$ABI

            cp Bin/Android/Libs/$ABI/$APP_NAME $ANDROID_JNILIBS_PATH/$ABI

            mkdir $ANDROID_ASSET_PATH

            cp Bin/BuiltIn.zip $ANDROID_ASSET_PATH

            cp Bin/Common.zip $ANDROID_ASSET_PATH

            cp Bin/SampleModelsResource.zip $ANDROID_ASSET_PATH

            cp Bin/SampleModelsETC.zip $ANDROID_ASSET_PATH

            cd Projects/Android

            ls -l $ANDROID_HOME

            chmod +x ./gradlew

            ./gradlew assembleDebug
          name: Build Android APK
jobs:
  build-android:
    docker:
      - image: cimg/android:2024.01.1-ndk
    environment:
      ABI: arm64-v8a
      APP_NAME: libSampleSkinnedMesh.so
    steps:
      - checkout
      - build-engine-native
      - build-asset-bundles
      - build-android-apk
workflows:
  version: 2
  build_all:
    jobs:
      - build-android
