version: 2.1

commands:  
  build-engine-native:
    steps:
      - run:
          command: >
            export ABI=arm64-v8a

            cmake -S. -BPrjAndroid-$ABI -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=$ABI -DANDROID_ARM_NEON=ON -DANDROID_NATIVE_API_LEVEL=26

            make -C PrjAndroid-$ABI
          name: Build Skylicht Engine Native SDK
jobs:
  build-android:
    docker:
      - image: cimg/android:2024.04.1-ndk
    steps:
      - checkout
      - build-engine-native
workflows:
  version: 2
  build_all:
    jobs:
      - build-android
