version: 2.1

commands:  
  build-engine-native:
    steps:
      - run:
          command: >
            cmake -S. -BPrjAndroid-$ABI -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=$ABI -DANDROID_ARM_NEON=ON -DANDROID_NATIVE_API_LEVEL=26

            make -C PrjAndroid-$ABI
          name: Build Skylicht Engine (NDK)
  build-asset-bundles:
    steps:
      - run:
          command:  > 
            cd Assets

            chmod +x ../Tools/PVRTexTool/linux/PVRTexToolCLI

            sudo apt-get update
            
            sudo apt install python3

            sudo apt install python3-pip

            pip3 install tinydb
          
            pip3 install Pillow

            python3 BuildTextureCompressETC.py

            python3 BuildAssetBundles.py

            cd ..
          name: Build Assets, ETC Textures
  build-android-apk:
    steps:
      - run:
          command: >
            export ANDROID_ASSET_PATH=Projects/Android/app/src/main/assets

            export ANDROID_JNILIBS_PATH=Projects/Android/app/src/main/jniLibs

            mkdir $ANDROID_JNILIBS_PATH

            mkdir $ANDROID_JNILIBS_PATH/$ABI

            cp Bin/Android/Libs/$ABI/$APP_NAME $ANDROID_JNILIBS_PATH/$ABI

            cp Bin/BuiltIn.zip $ANDROID_ASSET_PATH

            cp Bin/Common.zip $ANDROID_ASSET_PATH

            cp Bin/SampleModelsResource.zip $ANDROID_ASSET_PATH

            cp Bin/SampleModelsETC.zip $ANDROID_ASSET_PATH

            cd Projects/Android

            chmod +x ./gradlew

            ./gradlew assembleDebug

            ls app/build/outputs/apk/debug

            cd ../..
          name: Build Android APK
  build-android-aab:
    steps:
        - run:
            command: >
              export ANDROID_BUNDLE_PATH=Projects/Android/appdata/src/main/assets

              rm ANDROID_ASSET_PATH/*.zip

              export ANDROID_ASSET_PATH=Projects/Android/app/src/main/assets

              cp Bin/BuiltIn.zip $ANDROID_BUNDLE_PATH

              cp Bin/Common.zip $ANDROID_BUNDLE_PATH

              cp Bin/SampleModelsResource.zip $ANDROID_BUNDLE_PATH

              cp Bin/SampleModelsETC.zip $ANDROID_BUNDLE_PATH

              cd Projects/Android

              chmod +x ./gradlew

              ./gradlew bundleDebug

              ls app/build/outputs/bundle/debug

              cd ../..
            name: Build Android AAB
jobs:
  build-android:
    docker:
      - image: cimg/android:2024.01.1-ndk
    environment:
      ABI: arm64-v8a
      APP_NAME: libSampleSkinnedMesh.so
    steps:
      - checkout
      - build-engine-native
      - build-asset-bundles
      - build-android-apk
      - build-android-aab
workflows:
  version: 2
  build_all:
    jobs:
      - build-android
