name: C/C++ CI

on: [push]

jobs:
  Emscripten:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        git pull
        ./emsdk install latest-fastcomp
        ./emsdk activate latest-fastcomp
        source ./emsdk_env.sh
        ls -l fastcomp/emscripten/system/include
        cd ..
        wget -q https://github.com/emscripten-ports/SDL2/archive/version_18.zip
        tar -xvf SDL2-version_18.zip
        mkdir InstallLibs
        mkdir InstallLibs/SDL2
        cp -p ./SDL2-version_18/include/*.* ./InstallLibs/SDL2/
        
    - name: Build
      run: |        
        cmake -DCMAKE_TOOLCHAIN_FILE=emsdk/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake  -S.
        make
        
    - name: Package
      run: |
        mkdir Build
        7z a Build/Output.zip ./Bin/Emscripten/Libs/*.a
        
  Linux:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libsdl2-dev
        cmake --version
      
    - name: Build
      run: |
        cmake -S. -DBUILD_SDL=true
        make
      
    - name: Package
      run: |
        mkdir Build
        7z a Build/Output.zip ./Bin/Linux/Libs/*.a