name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libsdl2-dev
        cmake --version
      
    - name: Build
      run: |
        cmake -S . -D BUILD_SDL
        make
      
    - name: Zip
      run: |
        ls -l ./Bin
        7z a Output.zip ./Bin/*.a
