name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libsdl2-dev gcc-multilib g++-multilib
      
    - name: Build
      run: |
        cmake -S . -B ./PrjGCC
        make -C PrjGCC
      
    - name: Zip
        ls -l ./Bin
