name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libsdl2-dev
        cmake --version
      
    - name: Build
      run: |
        cmake -S. -DBUILD_SDL=true
        make
      
    - name: Zip
      run: |
        mkdir Build
        7z a Build/Output.zip ./Bin/Linux/Libs/*.a
